# Generated by Django 5.2.1 on 2025-07-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartdevices',
            name='beekeeper',
            field=models.ForeignKey(blank=True, help_text='The beekeeper who owns this device', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.beekeeperprofile'),
        ),
    ]
