# Generated by Django 5.2.1 on 2025-07-02 18:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('Temperature', 'Temperature'), ('Humidity', 'Humidity'), ('Weight', 'Weight'), ('Inspection_Due', 'Inspection Due'), ('Pest_Risk', 'Pest Risk'), ('Swarm_Risk', 'Swarm Risk')], max_length=20)),
                ('message', models.TextField(help_text='Descriptive message about the alert')),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10)),
                ('trigger_values', models.JSONField(blank=True, help_text='JSON data containing the values that triggered this alert', null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the alert was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='apiaries.hives')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Harvests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
                ('honey_kg', models.DecimalField(decimal_places=2, help_text='Amount of honey harvested in kilograms', max_digits=5, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)])),
                ('wax_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Amount of wax harvested in kilograms', max_digits=4, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=4)])),
                ('pollen_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Amount of pollen harvested in kilograms', max_digits=4, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=4)])),
                ('processing_method', models.CharField(blank=True, help_text='Method used for processing the harvest', max_length=100, null=True)),
                ('quality_notes', models.TextField(blank=True, help_text='Notes about the quality of the harvest', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('harvested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests_conducted', to=settings.AUTH_USER_MODEL)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='apiaries.hives')),
            ],
            options={
                'verbose_name': 'Harvest',
                'verbose_name_plural': 'Harvests',
                'ordering': ['-harvest_date', '-created_at'],
            },
        ),
    ]
