# Generated by Django 5.2.1 on 2025-07-03 09:42

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_superuser(apps, schema_editor):
    """Create default superuser if it doesn't exist"""
    User = apps.get_model('accounts', 'User')
    
    # Check if superuser already exists
    if not User.objects.filter(email='amazingjimmy44@gmail.com').exists():
        User.objects.create(
            email='amazingjimmy44@gmail.com',
            password=make_password('Amazing44.'),
            first_name='Jimmy',
            last_name='Admin',
            is_staff=True,
            is_superuser=True,
            is_active=True
        )
        print("✅ Superuser created successfully!")
        print("   Email: amazingjimmy44@gmail.com")
        print("   Name: Jimmy Admin")
    else:
        print("ℹ️  Superuser already exists, skipping creation.")


def reverse_create_superuser(apps, schema_editor):
    """Remove the created superuser (for migration rollback)"""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email='amazingjimmy44@gmail.com').delete()
    print("🗑️  Superuser removed.")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RunPython(
            create_superuser,
            reverse_create_superuser
        ),
    ]
