# Generated by Django 5.2.1 on 2025-07-02 16:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionSchedules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(help_text='Date when the inspection is scheduled')),
                ('notes', models.TextField(blank=True, help_text='Notes or instructions for the inspection', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the inspection has been completed')),
                ('weather_conditions', models.CharField(blank=True, help_text='Weather conditions for the scheduled inspection', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_schedules', to='apiaries.hives')),
            ],
            options={
                'verbose_name': 'Inspection Schedule',
                'verbose_name_plural': 'Inspection Schedules',
                'db_table': 'inspection_schedules',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_date', models.DateField(help_text='Date when the inspection was conducted')),
                ('queen_present', models.BooleanField(blank=True, help_text='Whether the queen was observed during inspection', null=True)),
                ('honey_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], help_text='Level of honey stores in the hive', max_length=10)),
                ('colony_health', models.CharField(choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent')], help_text='Overall health assessment of the colony', max_length=10)),
                ('varroa_mite_count', models.IntegerField(blank=True, help_text='Number of varroa mites observed', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('brood_pattern', models.CharField(choices=[('Solid', 'Solid'), ('Spotty', 'Spotty'), ('None', 'None')], help_text='Pattern of brood development', max_length=10)),
                ('pest_observations', models.TextField(blank=True, help_text='Observations about pests or diseases', null=True)),
                ('actions_taken', models.TextField(blank=True, help_text='Actions taken during the inspection', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the inspection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='apiaries.hives')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, help_text='Associated inspection schedule (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='inspections.inspectionschedules')),
            ],
            options={
                'verbose_name': 'Inspection Report',
                'verbose_name_plural': 'Inspection Reports',
                'db_table': 'inspection_reports',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
