# Generated by Django 5.2.3 on 2025-07-02 11:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apiaries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, validators=[django.core.validators.DecimalValidator(decimal_places=8, max_digits=10)])),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, validators=[django.core.validators.DecimalValidator(decimal_places=8, max_digits=11)])),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('beekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiaries', to='accounts.beekeeperprofile')),
            ],
            options={
                'verbose_name': 'Apiary',
                'verbose_name_plural': 'Apiaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hives',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Langstroth', 'Langstroth'), ('Top-Bar', 'Top-Bar'), ('Warre', 'Warre'), ('Other', 'Other')], default='Langstroth', max_length=20)),
                ('installation_date', models.DateField()),
                ('has_smart_device', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='apiaries.apiaries')),
            ],
            options={
                'verbose_name': 'Hive',
                'verbose_name_plural': 'Hives',
                'ordering': ['-created_at'],
            },
        ),
    ]
